ALTER POLICY "tenant_isolation" ON "accounts" TO public USING ("accounts"."user_id" = nullif(current_setting('app.current_user_id', true), '')::uuid) WITH CHECK ("accounts"."user_id" = nullif(current_setting('app.current_user_id', true), '')::uuid);--> statement-breakpoint
ALTER POLICY "tenant_isolation" ON "budgets" TO public USING ("budgets"."user_id" = nullif(current_setting('app.current_user_id', true), '')::uuid) WITH CHECK ("budgets"."user_id" = nullif(current_setting('app.current_user_id', true), '')::uuid);--> statement-breakpoint
ALTER POLICY "tenant_isolation" ON "category_budgets" TO public USING ("category_budgets"."user_id" = nullif(current_setting('app.current_user_id', true), '')::uuid) WITH CHECK ("category_budgets"."user_id" = nullif(current_setting('app.current_user_id', true), '')::uuid);--> statement-breakpoint
ALTER POLICY "tenant_isolation" ON "savings_envelopes" TO public USING ("savings_envelopes"."user_id" = nullif(current_setting('app.current_user_id', true), '')::uuid) WITH CHECK ("savings_envelopes"."user_id" = nullif(current_setting('app.current_user_id', true), '')::uuid);--> statement-breakpoint
ALTER POLICY "tenant_isolation" ON "categories" TO public USING ("categories"."user_id" = nullif(current_setting('app.current_user_id', true), '')::uuid) WITH CHECK ("categories"."user_id" = nullif(current_setting('app.current_user_id', true), '')::uuid);--> statement-breakpoint
ALTER POLICY "tenant_isolation" ON "card_transactions" TO public USING ("card_transactions"."user_id" = nullif(current_setting('app.current_user_id', true), '')::uuid) WITH CHECK ("card_transactions"."user_id" = nullif(current_setting('app.current_user_id', true), '')::uuid);--> statement-breakpoint
ALTER POLICY "tenant_isolation" ON "credit_cards" TO public USING ("credit_cards"."user_id" = nullif(current_setting('app.current_user_id', true), '')::uuid) WITH CHECK ("credit_cards"."user_id" = nullif(current_setting('app.current_user_id', true), '')::uuid);--> statement-breakpoint
ALTER POLICY "tenant_isolation" ON "invoices" TO public USING ("invoices"."user_id" = nullif(current_setting('app.current_user_id', true), '')::uuid) WITH CHECK ("invoices"."user_id" = nullif(current_setting('app.current_user_id', true), '')::uuid);--> statement-breakpoint
ALTER POLICY "tenant_isolation" ON "import_batches" TO public USING ("import_batches"."user_id" = nullif(current_setting('app.current_user_id', true), '')::uuid) WITH CHECK ("import_batches"."user_id" = nullif(current_setting('app.current_user_id', true), '')::uuid);--> statement-breakpoint
ALTER POLICY "tenant_isolation" ON "installment_plans" TO public USING ("installment_plans"."user_id" = nullif(current_setting('app.current_user_id', true), '')::uuid) WITH CHECK ("installment_plans"."user_id" = nullif(current_setting('app.current_user_id', true), '')::uuid);--> statement-breakpoint
ALTER POLICY "tenant_isolation" ON "recurrence_rules" TO public USING ("recurrence_rules"."user_id" = nullif(current_setting('app.current_user_id', true), '')::uuid) WITH CHECK ("recurrence_rules"."user_id" = nullif(current_setting('app.current_user_id', true), '')::uuid);--> statement-breakpoint
ALTER POLICY "tenant_isolation" ON "tags" TO public USING ("tags"."user_id" = nullif(current_setting('app.current_user_id', true), '')::uuid) WITH CHECK ("tags"."user_id" = nullif(current_setting('app.current_user_id', true), '')::uuid);--> statement-breakpoint
ALTER POLICY "tenant_isolation" ON "transaction_tags" TO public USING ("transaction_tags"."user_id" = nullif(current_setting('app.current_user_id', true), '')::uuid) WITH CHECK ("transaction_tags"."user_id" = nullif(current_setting('app.current_user_id', true), '')::uuid);--> statement-breakpoint
ALTER POLICY "tenant_isolation" ON "transactions" TO public USING ("transactions"."user_id" = nullif(current_setting('app.current_user_id', true), '')::uuid) WITH CHECK ("transactions"."user_id" = nullif(current_setting('app.current_user_id', true), '')::uuid);